// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCghVNutEtO6hThJpPoCY_Kv79afZS-B3Y',
    appId: '1:435145274657:web:0359a505ea36c29840ba60',
    messagingSenderId: '435145274657',
    projectId: 'week8-data-persistence-8c57b',
    authDomain: 'week8-data-persistence-8c57b.firebaseapp.com',
    storageBucket: 'week8-data-persistence-8c57b.appspot.com',
    measurementId: 'G-3JWLSL7JD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD77ORhDmVMJmRL6cOSkqb3-dCazdAK2xA',
    appId: '1:435145274657:android:88a877420f9d583740ba60',
    messagingSenderId: '435145274657',
    projectId: 'week8-data-persistence-8c57b',
    storageBucket: 'week8-data-persistence-8c57b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaDnc4ly6OK8unomvRILYOkwZhTi02YTs',
    appId: '1:435145274657:ios:f329c27214576bda40ba60',
    messagingSenderId: '435145274657',
    projectId: 'week8-data-persistence-8c57b',
    storageBucket: 'week8-data-persistence-8c57b.appspot.com',
    iosBundleId: 'com.example.week9Authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaDnc4ly6OK8unomvRILYOkwZhTi02YTs',
    appId: '1:435145274657:ios:f329c27214576bda40ba60',
    messagingSenderId: '435145274657',
    projectId: 'week8-data-persistence-8c57b',
    storageBucket: 'week8-data-persistence-8c57b.appspot.com',
    iosBundleId: 'com.example.week9Authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCghVNutEtO6hThJpPoCY_Kv79afZS-B3Y',
    appId: '1:435145274657:web:db72a8a8b3c3a74540ba60',
    messagingSenderId: '435145274657',
    projectId: 'week8-data-persistence-8c57b',
    authDomain: 'week8-data-persistence-8c57b.firebaseapp.com',
    storageBucket: 'week8-data-persistence-8c57b.appspot.com',
    measurementId: 'G-LQ2P5C7W42',
  );
}
